Finishing details
SU-UTB/web-sutb pull request #9
Opened 2023-02-27 20:42 UTC by ondrasalek

Header style edit: created hamburger menu

Footer style edit: centering Kontakty

Body style: hero sizes on screen resize, and margin content

2023-02-27 22:22 UTC, tomesfilip requested changes
- by any chance, don't we have SU logos in .svg format? would be better..
- idk if we want to have .css files still present or if we want to fully use the potential of styled components. Instead of index.css there might be global.ts file in some /styles folder with global css definitions.

2023-02-27 22:22 UTC, tomesfilip commented on src/components/articles/Article.tsx
> +        <Wrapper primary={margin} isMobile={isMobile}>
I'd say, there is no need for this parameter, and can be easily adjusted using media queries in Article.styled.tsx

2023-02-27 22:22 UTC, tomesfilip commented on src/components/layout/header/Header.styled.tsx
> +        font-weight: normal;
same here, rather use numeric value instead of normal

2023-02-27 23:44 UTC, ondrasalek commented
Everything @tomesfilip comments is fixed now

2023-02-28 08:23 UTC, SedlarDavid approved these changes

2023-02-28 08:23 UTC, SedlarDavid commented on .github/workflows/firebase-hosting-merge.yml
> +# This file was auto-generated by the Firebase CLI
Its better to separate context of files into separate PRs 
e.g.
PR for firebase addition
PR for refactoring
PR for styling
and so on, but  its just a hint

2023-03-02 16:10 UTC, tomesfilip approved these changes
GJ

2023-03-02 16:11 UTC, merged